name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Code check (${{ matrix.script }})
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: true
      matrix:
        script: [format]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-node-dependencies

      - name: Run ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}

  ci-ok:
    name: CI OK
    runs-on: ubuntu-latest
    if: always()
    needs: [check]
    env:
      FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
      CANCELLED: ${{ contains(join(needs.*.result, ','), 'cancelled') }}
    steps:
      - name: Check for failure or cancelled jobs result
        shell: bash
        run: |
          echo "Failure: $FAILURE - Cancelled: $CANCELLED"
          if [ "$FAILURE" = "false" ] && [ "$CANCELLED" = "false" ]; then
            exit 0
          else
            exit 1
          fi
